FROM docker.elastic.co/elasticsearch/elasticsearch:7.5.1
USER root
RUN chown elasticsearch:elasticsearch config/elasticsearch.yml
USER elasticsearch


ADD ./es_scripts/ /usr/share/elasticsearch/config/scripts
