version: '2'

services:
  client:
    build: ./client
    container_name: client
    command: npm start
    ports:
      - '3000:3000'
    networks:
      - images

  server: 
    build: ./
    restart: unless-stopped
    container_name: server
    command: python server.py
    ports: 
      - '8081:8081'
    volumes:
      - '.:/app'
    networks:
      - images
      - esnet
  
  elasticsearch:
    build:
      context: ./
      dockerfile: Dockerfile-elastic
    ports:
      - '9200:9200'
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet
  
  indexer:
    build:
      context: ./
      dockerfile: ./scripts/Dockerfile
    container_name: indexer
    networks:
      - esnet

volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge
  images:
  